
server:
  port: ${SERVER_PORT:8080}
spring:
  
  datasource:
    url: ${MYSQL_DB_URL:jdbc:mysql://localhost:3306/backend?characterEncoding=utf-8}
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    # กำหนกให้แสดงคำสั่ง SQL บน terminal
    # ภาษา SQL แบ่งคำสั่งออกเป็น 2 ส่วน
    # 1 ส่วนที่นิยามข้อมูล (Data Definition Language: DDL) เช่น คำสั่ง create/alter/drop table
    # 2 ส่วนจัดการข้อมูล (Data Manipulation Language: DML) เช่น คำสั่ง select , insert, update, delete
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

backend:
  jwt:
#    Y M W D H MM S MS
#    * * * * * *  * *
#    15 * 60 *  1000 << output 900000 // 15min
    expired: 900000
    secret-key: ${PRIVATE_KEY:d45c48a62cfcf0c885b1865088f14e6dc1d075383bfaf879079fee4c1aef0ef6}
    public-key: ${PUBLIC_KEY:public-key}

APPLICATION:
  MOUNT_PATH: src/main/resources/opt/stores
